/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rw.gorv.employeemgt.view;

import java.util.Date;
import rw.gorv.employeemgt.dao.EmployeeDao;
import rw.gorv.employeemgt.model.Employee;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import rw.gorv.employeemgt.dao.EmployeeDetailsDao;
import rw.gorv.employeemgt.model.EmployeeDetails;

/**
 *
 * @author jeremie
 */
public class App extends javax.swing.JFrame {
    DefaultTableModel tableModel = new DefaultTableModel();
    /**
     * Creates new form App
     */
    public App() {
        initComponents();
        employeeDetIdTxt.setText(employeeIdTxt.getText());
        employeeDetIdTxt.setEnabled(false);
        addColumnsHeaderNameToTable();
        addRowsDataToTable();
        
    }
    
    // method to add columnsHeader name
    private void addColumnsHeaderNameToTable(){
        tableModel.addColumn("Employee ID");
        tableModel.addColumn("First Name");
        tableModel.addColumn("First Name");
        tableModel.addColumn("Last Name");
        tableModel.addColumn("Active");
        employeeTable.setModel(tableModel);
    }
    
    private void addRowsDataToTable(){
        tableModel.setRowCount(0);
        EmployeeDao dao = new EmployeeDao();
        List<Employee> employees = dao.retrieveAllEMployee();
        for(Employee theEmployee : employees){
            if (theEmployee != null)
                tableModel.addRow(theEmployee.data2table());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        employeeIdTxt = new javax.swing.JTextField();
        firstNameTxt = new javax.swing.JTextField();
        registerBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        lastNameTxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        employeePhoneNumberTxt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        employeeDetIdTxt = new javax.swing.JTextField();
        employeeEmmergencyContactTxt = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        searchIdTxt = new javax.swing.JTextField();
        searchBtn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        employeeTable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        jLabel1.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        jLabel1.setText("Registration Page");

        jLabel2.setText("Employee ID");

        jLabel3.setText("First Name");

        employeeIdTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        firstNameTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        registerBtn.setText("Register");
        registerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerBtnActionPerformed(evt);
            }
        });

        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        lastNameTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel6.setText("Last Name");

        jLabel7.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        jLabel7.setText("Employee Details");

        employeePhoneNumberTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel8.setText("Phone Number");

        jLabel9.setText("Emmergency Contact");

        jLabel10.setText("Details ID");

        employeeDetIdTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        employeeEmmergencyContactTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel8)
                                .addComponent(jLabel9)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel3))
                                .addGap(60, 60, 60)))
                        .addGap(95, 95, 95)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lastNameTxt)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(firstNameTxt)
                                .addComponent(employeeIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(employeePhoneNumberTxt)
                                .addComponent(employeeEmmergencyContactTxt)
                                .addComponent(employeeDetIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(77, 77, 77))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addComponent(jLabel7))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(registerBtn)
                                .addGap(28, 28, 28)
                                .addComponent(updateBtn)
                                .addGap(46, 46, 46)
                                .addComponent(deleteBtn)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(employeeIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(firstNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(lastNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel2)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(employeeDetIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(employeeEmmergencyContactTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(employeePhoneNumberTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registerBtn)
                    .addComponent(updateBtn)
                    .addComponent(deleteBtn))
                .addGap(21, 21, 21))
        );

        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        jLabel4.setText("Employee ID");

        searchBtn.setText("Search");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel4)
                .addGap(42, 42, 42)
                .addComponent(searchIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(searchBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(searchIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchBtn))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        jLabel5.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        jLabel5.setText("Employee DataTable");

        employeeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(employeeTable);

        jButton1.setText("Refresh");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 167, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(40, 40, 40))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel5))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerBtnActionPerformed
        
        try{
            // make all field required
            if(employeeIdTxt.getText().trim().isEmpty()){
                JOptionPane.showMessageDialog(this, "Employee ID is required");
            }else if(firstNameTxt.getText().trim().isEmpty()){
                JOptionPane.showMessageDialog(this, "Employee Name is required");
            }else{
                // 2 validation rule
                if(firstNameTxt.getText().length() >=3){
                    int id = Integer.parseInt(employeeIdTxt.getText());
                    // Capture Data entered by user
                    EmployeeDetails empDetails = new EmployeeDetails();
                    empDetails.setEmmergencyContact(employeeEmmergencyContactTxt.getText());
                    empDetails.setPhoneNumber(employeePhoneNumberTxt.getText());
                    // dao
                    EmployeeDetailsDao empDetailsDao = new EmployeeDetailsDao();
                    empDetails = empDetailsDao.registerEmployeeDetails(empDetails);
                    
                    Employee theEmployee = new Employee();
                    theEmployee.setEmpId(id);
                    theEmployee.setEmpDetails(empDetails);
                    theEmployee.setActive(true);
                    theEmployee.setStartDate(new Date());
                    theEmployee.setFirstName(firstNameTxt.getText());
                    theEmployee.setLastName(lastNameTxt.getText());
                    // calling DAO
                    EmployeeDao dao = new EmployeeDao();
                    Employee emp  = dao.registerEmployee(theEmployee);
                    if(emp!=null){
                        JOptionPane.showMessageDialog(this, "Data Saved Successful");
                        addRowsDataToTable();
                        employeeIdTxt.setText("");
                        firstNameTxt.setText("");
                        lastNameTxt.setText("");
                        employeeDetIdTxt.setText("");
                        employeeEmmergencyContactTxt.setText("");
                        employeePhoneNumberTxt.setText("");
                    }else{
                        JOptionPane.showMessageDialog(this, "Data Not Saved Successful");
                    }
                }else{
                    JOptionPane.showMessageDialog(this, "Employee Name must equal or above 3 characters");
                }
                
            }
        }catch(Exception ex){
            ex.printStackTrace();
        }
        
    }//GEN-LAST:event_registerBtnActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        try{
            if(searchIdTxt.getText().trim().isEmpty()){
                JOptionPane.showMessageDialog(this, "Employee ID to search is required");
            }else{
                
                
                int id = Integer.parseInt(searchIdTxt.getText());
                Employee theEmployee = new Employee(id);
                
                EmployeeDao dao = new EmployeeDao();
                Employee empObj = dao.findEmployeeById(theEmployee);
                if(empObj!=null){
                    
                    employeeIdTxt.setText(empObj.getEmpId().toString());
                    firstNameTxt.setText(empObj.getFirstName());
                    lastNameTxt.setText(empObj.getLastName());
                    EmployeeDetails empDetails = empObj.getEmpDetails();
                    if (empDetails != null){
                        employeeDetIdTxt.setText(String.valueOf(empDetails.getEmpDetId()));
                        employeeEmmergencyContactTxt.setText(empDetails.getEmmergencyContact());
                        employeePhoneNumberTxt.setText(empDetails.getPhoneNumber());
                    }
                    
                }else{
                    JOptionPane.showMessageDialog(this, "Data not found");
                }
            }
        }catch(Exception ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_searchBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        try{
            // make all field required
            if(employeeIdTxt.getText().trim().isEmpty()){
                JOptionPane.showMessageDialog(this, "Employee ID is required");
            }else if(firstNameTxt.getText().trim().isEmpty()){
                JOptionPane.showMessageDialog(this, "Employee Name is required");
            }else{
                // 2 validation rule
                if(firstNameTxt.getText().length() >=3){
                    int id = Integer.parseInt(employeeIdTxt.getText());
                    Employee theEmployee = new Employee();
                    theEmployee.setEmpId(id);
                    // calling DAO
                    EmployeeDao dao = new EmployeeDao();
                    Employee empfound  = dao.findEmployeeById(theEmployee);
                    if (empfound != null){
                        EmployeeDetails empDetails = new EmployeeDetails();
                        // dao
                        // update employee details
                        EmployeeDetailsDao empDetailsDao = new EmployeeDetailsDao();
                        empDetails = empDetailsDao.findEmployeeDetailsById(empfound.getEmpDetails());
                        if (empDetails != null){
                            empDetails.setEmmergencyContact(employeeEmmergencyContactTxt.getText());
                            empDetails.setPhoneNumber(employeePhoneNumberTxt.getText());
                            empDetails = empDetailsDao.updateEmployeeDetails(empDetails);
                            
                            // update employee info
                            theEmployee.setEmpDetails(empDetails);
                            theEmployee.setActive(true);
                            theEmployee.setStartDate(new Date());
                            theEmployee.setFirstName(firstNameTxt.getText());
                            theEmployee.setLastName(lastNameTxt.getText());
                            Employee emp  = dao.updateEmployee(theEmployee);
                            if(emp!=null){
                                JOptionPane.showMessageDialog(this, "Data Updated Successful");
                                addRowsDataToTable();
                                employeeIdTxt.setText("");
                                firstNameTxt.setText("");
                                lastNameTxt.setText("");
                                employeeDetIdTxt.setText("");
                                employeeEmmergencyContactTxt.setText("");
                                employeePhoneNumberTxt.setText("");

                            }
                        }
                        
                    }
                    else{
                        JOptionPane.showMessageDialog(this, "Data Not Updated ");
                    }
                }else{
                    JOptionPane.showMessageDialog(this, "Employee Name must equal or above 3 characters");
                }
                
            }
        }catch(Exception ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_updateBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        try {
            if (employeeIdTxt.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Employee ID is required");
                return;
            }

            int id = Integer.parseInt(employeeIdTxt.getText());
            Employee theEmployee = new Employee();
            theEmployee.setEmpId(id);

            EmployeeDao dao = new EmployeeDao();
            Employee empfound = dao.findEmployeeById(theEmployee);

            if (empfound != null) {
                EmployeeDetails empDetails = empfound.getEmpDetails();

                // Ensure empDetails is not null before attempting to delete it
                if (empDetails != null) {
                    EmployeeDetailsDao empDetDao = new EmployeeDetailsDao();
                    empDetails = empDetDao.deleteEmployeeDetails(empDetails);
                }

                // Delete the employee
                Employee emp = dao.deleteEmployee(empfound);

                if (emp != null) {
                    JOptionPane.showMessageDialog(this, "Data Deleted Successful");
                    addRowsDataToTable();
                    employeeIdTxt.setText("");
                    firstNameTxt.setText("");
                    lastNameTxt.setText("");
                    employeeDetIdTxt.setText("");
                    employeeEmmergencyContactTxt.setText("");
                    employeePhoneNumberTxt.setText("");
                } else {
                    JOptionPane.showMessageDialog(this, "Data Not Deleted");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Employee not found");
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }

    }//GEN-LAST:event_deleteBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new App().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deleteBtn;
    private javax.swing.JTextField employeeDetIdTxt;
    private javax.swing.JTextField employeeEmmergencyContactTxt;
    private javax.swing.JTextField employeeIdTxt;
    private javax.swing.JTextField employeePhoneNumberTxt;
    private javax.swing.JTable employeeTable;
    private javax.swing.JTextField firstNameTxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lastNameTxt;
    private javax.swing.JButton registerBtn;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTextField searchIdTxt;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
